USE [master]
GO

/****** Object:  Database [Simpoll]    Script Date: 16/01/2018 14:14:19 ******/
CREATE DATABASE [Simpoll]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Simpoll', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Simpoll.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Simpoll_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Simpoll_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Simpoll] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Simpoll].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Simpoll] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Simpoll] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Simpoll] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Simpoll] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Simpoll] SET ARITHABORT OFF 
GO

ALTER DATABASE [Simpoll] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Simpoll] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Simpoll] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Simpoll] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Simpoll] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Simpoll] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Simpoll] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Simpoll] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Simpoll] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Simpoll] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Simpoll] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Simpoll] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Simpoll] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Simpoll] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Simpoll] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Simpoll] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Simpoll] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Simpoll] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Simpoll] SET  MULTI_USER 
GO

ALTER DATABASE [Simpoll] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Simpoll] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Simpoll] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Simpoll] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Simpoll] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Simpoll] SET QUERY_STORE = OFF
GO

USE [Simpoll]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Simpoll] SET  READ_WRITE 
GO


